/**
 * Browser-connector tool surface: one tool list, generated by the same
 * buildServer that serves the ChatGPT connector, plus prompt-protocol
 * instructions and a direct execution path through the kernel.
 */

import { getConfig, effectiveCapabilities } from '../config.js';
import { createRegistrar, dispatchWithKnownCaller, fail, friendlyError, type ToolContext, type ToolResult } from '../mcp/kernel.js';import type { PluginToolSchema } from '../../shared/plugin-refresh.js';
import type { McpServer } from '@modelcontextprotocol/server';

/** Transport key recorded for browser-connector calls in kernel evidence. */
export const BROWSER_TRANSPORT_PREFIX = 'browser:';

export interface BrowserToolCall {
  readonly tool: string;
  readonly args: Record<string, unknown>;
  readonly conversationId: string;
  readonly siteId: string;
}

/** The same ToolContext shape connection.ts hands the MCP endpoint. */
function liveContext(): ToolContext {
  const live = getConfig();
  return {
    roots: live.roots,
    caps: effectiveCapabilities(live),
    readOnly: live.readOnly,
    privacyScreenshots: live.ui.privacyScreenshots
  };
}

export interface BrowserToolCatalog {
  readonly instructions: string;
  readonly tools: PluginToolSchema[];
}

/**
 * Collects the exact tool list the ChatGPT connector advertises. Uses the same
 * buildServer publication path (see server.ts endpoint.publication) so the
 * browser connector and the ChatGPT connector can never drift apart.
 */
export async function browserToolCatalog(): Promise<BrowserToolCatalog> {
  // Lazy import: tools.js pulls tools-desktop.js -> kernel.js, and kernel.ts
  // already imports bridge.ts, so a static import here is an ESM cycle that
  // breaks module evaluation (mouseButtonArg TDZ). Load at call time instead.
  const { buildServer } = await import('../mcp/tools.js');
  const tools: PluginToolSchema[] = [];
  const server = buildServer(liveContext(), 'core', (_connector, _version, _instructions, schemaList) => {
    tools.push(...schemaList);
  });
  void server.close();
  return { instructions: browserInstructions(tools), tools };
}

/**
 * SuperAssistant-style prompt-protocol instructions (JSONL variant, the active
 * format in MCP-SuperAssistant). The model in a non-ChatGPT site has no native
 * tool calling, so this text teaches it the echo protocol the observer parses.
 */
export function browserInstructions(tools: readonly PluginToolSchema[]): string {
  if (!tools || tools.length === 0) {
    return '# No tools available\n\nConnect Chat On Steroids and approve a folder to see available tools.';
  }
  let out =
    '<SYSTEM>\n' +
    'You are SuperAssistant, a knowledgeable assistant that can invoke functions.\n' +
    'In this environment you have access to a set of functions you can use to answer the user\'s question.\n' +
    'Place every function call in a ```jsonl code block with exactly these line types:\n' +
    '{"type":"function_call_start","name":"$FUNCTION_NAME","call_id":$CALL_ID}\n' +
    '{"type":"description","text":"$SHORT_DESCRIPTION"}\n' +
    '{"type":"parameter","key":"$PARAMETER_NAME","value":$VALUE_JSON}\n' +
    '{"type":"function_call_end","call_id":$CALL_ID}\n' +
    'Rules:\n' +
    '1. Invoke only ONE function at a time (a single function_call_start..function_call_end block).\n' +
    '2. call_id is a number starting at 1 and incremented by 1 for each new call.\n' +
    '3. String/scalar parameters are written directly as JSON values; lists and objects use JSON too.\n' +
    '4. Wait for the execution result, which arrives in <function_result call_id="N">...</function_result> tags, then continue your answer.\n' +
    '5. NEVER invent functions that are not listed below.\n' +
    '6. NEVER mock a <function_result> yourself.\n' +
    '\n' +
    '## AVAILABLE TOOLS FOR SUPERASSISTANT\n';
  for (const tool of tools) {
    out += ` - ${tool.name}\n`;
    if (tool.description) out += `**Description**: ${tool.description}\n`;
    const schemaObj = (tool.inputSchema ?? {}) as {
      properties?: Record<string, { type?: string; description?: string }>;
      required?: string[];
    };
    const properties = schemaObj.properties ?? {};
    const required = Array.isArray(schemaObj.required) ? schemaObj.required : [];
    if (Object.keys(properties).length > 0) {
      out += '**Parameters**:\n';
      for (const [key, detail] of Object.entries(properties)) {
        const requiredFlag = required.includes(key) ? 'required' : 'optional';
        out += `- \`${key}\`: ${detail?.description ?? ''} (${detail?.type ?? 'any'}) (${requiredFlag})\n`;
      }
    }
    out += '\n';
  }
  out += '<\\SYSTEM>\n';
  return out;
}

let capturedHandlers: Promise<Map<string, (args: never) => Promise<ToolResult>>> | null = null;

/**
 * Captures the raw core-surface handlers once. Registration is idempotent:
 * tools-core only registers tools whose capabilities are live, matching what
 * browserToolCatalog advertises.
 */
async function browserHandlers(): Promise<Map<string, (args: never) => Promise<ToolResult>>> {
  if (!capturedHandlers) {
    const { registerCoreTools } = await import('../mcp/tools-core.js');
    const capture = new Map<string, (args: never) => Promise<ToolResult>>();
    const stub = { registerTool: () => undefined } as unknown as McpServer;
    const registrar = createRegistrar(stub, liveContext(), 'core', undefined, capture);
    registerCoreTools(registrar);
    capturedHandlers = Promise.resolve(capture);
  }
  return capturedHandlers;
}

/**
 * Executes one browser-connector tool call through the exact same kernel entry
 * as a ChatGPT call, with the conversation identity supplied by the connector
 * (session-scoped attribution, never request-id proven).
 */
/**
 * Returns the captured core-surface handler for one tool, or undefined.
 * Shared by browser and API connectors so every transport runs the same
 * kernel-backed implementation.
 */
export async function capturedCoreHandler(
  name: string
): Promise<((args: never) => Promise<ToolResult>) | undefined> {
  return (await browserHandlers()).get(name);
}

export async function executeBrowserTool(call: BrowserToolCall): Promise<ToolResult> {
  if (!call || typeof call.tool !== 'string' || call.tool.length === 0) {
    return fail('MISSING_TOOL: no tool name was supplied by the browser connector.');
  }
  if (typeof call.conversationId !== 'string' || call.conversationId.length === 0 || call.conversationId.length > 256) {
    return fail('MISSING_CONVERSATION: the browser connector could not identify the chat.');
  }
  // The connector key doubles as the recorded conversation id; anything outside
  // the session store's id rules would file the call under Unattributed noise.
  if (!/^[a-z0-9][a-z0-9-]{0,47}--[a-z0-9][a-z0-9_-]{3,80}$/i.test(call.conversationId)) {
    return fail('INVALID_CONVERSATION: the browser connector produced a conversation key outside the expected siteId--segment shape.');
  }
  const handler = (await browserHandlers()).get(call.tool);
  if (!handler) {
    return fail(
      `UNKNOWN_TOOL: '${call.tool}' is not available on this connector. ` +
        'Enable the matching permission in Chat On Steroids, then refresh the tool list.'
    );
  }
  const args = call.args && typeof call.args === 'object' ? call.args : {};
  try {
    return await dispatchWithKnownCaller(
      call.tool,
      args,
      call.conversationId,
      `${BROWSER_TRANSPORT_PREFIX}${call.siteId || 'unknown'}`,
      'core',
      (received) => handler(received as never)
    );
  } catch (err) {
    // guard() already converts handler failures; this covers failures the kernel
    // itself raises (identity, blocked chats) so the bridge route never 500s.
    return fail(friendlyError(err));
  }
}
